version: "3"

services:
  ftp:
    image: stilliard/pure-ftpd
    container_name: ftp-server

    ports:
      - "21:21"
      - "30000-30009:30000-30009"

    volumes:
      - ./data:/home/ftpusers
      - ./passwd:/etc/pure-ftpd/passwd

    environment:
      PUBLICHOST: localhost
      FTP_USER_NAME: user1
      FTP_USER_PASS: 1234
      FTP_USER_HOME: /home/ftpusers

    restart: always